/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ltm.lmt.view;
import com.ltm.lmt.view.ChatPanel;
import com.ltm.lmt.model.User;
import java.awt.Color;
import javax.swing.*;
/**
 *
 * @author Son
 */
public class ContentHome extends javax.swing.JPanel {

    public ContentHome() {
        initComponents();
        setLayout(null);
    }

    public void openChat(User currentUser, User selectedUser) {
        ChatPanel chatPanel = new ChatPanel(currentUser, selectedUser);
        addChatPanelToContentHome(chatPanel);
    }
    
    public void addChatPanelToContentHome(ChatPanel chatPanel) {
        chatPanel.setBounds(787, 416, 480, 360);
        this.add(chatPanel);
        this.revalidate();
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
